package com.project.core_service.models.process_compliance;

public enum StandardGuideline {
    CRYPTOGRAPHY_STANDARDS,
    ACCESS_CONTROL_STANDARDS,
    SOP_FOR_CODE_REVIEW,
    VA_AND_PT_STANDARDS,
    INFORMATION_CLASSIFICATION_STANDARDS,
    DATA_CONTROL_STANDARDS,
    CLOUD_SECURITY_STANDARDS,
    INTEGRATION_SECURITY_STANDARDS
}
